### ISSUE TITLE
Bootstrap node can not work

### ISSUE THREAD

**Issue by itachiliu** [BenDerPan/simple-bootstrap-node#4]
Hi When I start my own bootstrap node ，all node stay in
"2020-08-12T04:08:12.885+0800 INFO rendezvous chat-with-rendezvous/chat.go:160 Announcing ourselves..."
Is there something wrong about my operation? @BenDerPan can you help me？THX

**Comment by BenDerPan** [comment]
@itachiliu  Hi, it seems that it is incompatible with the new version of go-libp2p. maybe you can check out the diffirent part to make it compatible to solve this

**Comment by itachiliu** [comment]
> @itachiliu Hi, it seems that it is incompatible with the new version of go-libp2p. maybe you can check out the diffirent part to make it compatible to solve this

Thanks for your reply，I use the chat-with-rendezvous example，just change the bootstrap node list(delete original list,add my own node ID ),no other change. When I use the original list, it works properly, Do you have any  ideas about this condition？

**Comment by BenDerPan** [comment]
@itachiliu I think you can check you own node WAF, make sure you can visit your own node. if it's ok, then maybe it's the problem of you own node implementation.

**Comment by itachiliu** [comment]
> @itachiliu I think you can check you own node WAF, make sure you can visit your own node. if it's ok, then maybe it's the problem of you own node implementation.

Do you have any example about this，or your previous implementation， I want to make a comparison

**Comment by itachiliu** [comment]
I figure the problem.  Before  kad DHT package v0.5.0，The default mode of DHTs used to be "server", but after v0.5.0, the default is just a client (they can query, but not respond). The fix was to add the `dht.Mode(dht.ModeServer) `option as a parameter when calling `dht.New()`

**Comment by itachiliu** [comment]
Thank you for your replay ☺

**Comment by BenDerPan** [comment]
@itachiliu nice!

**Comment by bitcard** [comment]
> I figure the problem. Before kad DHT package v0.5.0，The default mode of DHTs used to be "server", but after v0.5.0, the default is just a client (they can query, but not respond). The fix was to add the `dht.Mode(dht.ModeServer) `option as a parameter when calling `dht.New()`

thank you
